import os

routes = [
    ('districts', 'District Monitoring', 'Map', 'Monitor health performance across all districts.', 'districts', ['Name', 'Population', 'Hospitals', 'PHCs', 'CHCs', 'Health Score', 'Status']),
    ('hospitals', 'State Hospitals', 'Building2', 'Overview of all district hospitals and medical colleges.', 'hospitals', ['Hospital Name', 'District', 'Type', 'Beds Occupied', 'Doctors', 'Status']),
    ('phcs', 'Primary Health Centers', 'MapPin', 'Monitor PHC performance and coverage.', 'districts', ['District', 'Total PHCs', 'Doctors Present', 'Medicine Stock', 'Status']),
    ('chcs', 'Community Health Centers', 'MapPin', 'Monitor CHC performance and coverage.', 'districts', ['District', 'Total CHCs', 'Beds Occupied', 'Medicine Stock', 'Status']),
    ('medicine', 'Medicine Supply Chain', 'Pill', 'Statewide tracking of medicine stock and distribution.', 'districts', ['District', 'Total Stock', 'Critical Shortages', 'AI Recommendation', 'Status']),
    ('beds', 'Bed Capacity', 'Bed', 'Real-time bed occupancy across the state.', 'hospitals', ['Hospital', 'Total Beds', 'Occupied', 'Available', 'Status']),
    ('workforce', 'Doctor Workforce', 'UserCheck', 'Manage healthcare professionals deployment and attendance.', 'districts', ['District', 'Total Doctors', 'Present', 'Vacancies', 'Status']),
    ('surveillance', 'Disease Surveillance', 'Activity', 'Monitor outbreaks and disease trends statewide.', 'alerts', ['Time', 'District', 'Alert Title', 'Severity', 'Description']),
    ('emergency', 'Emergency Response', 'AlertTriangle', 'Coordinate statewide emergency response and ambulance routing.', 'alerts', ['Time', 'District', 'Emergency', 'Severity', 'Details']),
    ('ai', 'AI Command Center', 'Bot', 'State-level predictive analytics and automated recommendations.', 'districts', ['District', 'AI Forecast', 'Recommendation', 'Health Score', 'Risk Level']),
    ('allocation', 'Resource Allocation', 'ArrowLeftRight', 'Approve and manage statewide resource redistributions.', 'allocations', ['Resource', 'From District', 'To District', 'Quantity', 'Status']),
    ('analytics', 'Analytics', 'BarChart2', 'Comprehensive healthcare analytics and insights.', 'districts', ['Metric', 'Current Value', 'Trend', 'Prediction']),
    ('reports', 'State Reports', 'FileText', 'Export and manage official state health reports.', 'districts', ['Report Name', 'Date', 'Type', 'Generated By', 'Action']),
    ('policies', 'Policies & Guidelines', 'ShieldCheck', 'Manage government circulars and compliance protocols.', 'districts', ['Policy', 'Date', 'Applies To', 'Compliance Rate', 'Status']),
    ('notifications', 'Notifications', 'Bell', 'View critical alerts and system notifications.', 'alerts', ['Date', 'Title', 'Severity', 'Description']),
    ('sync', 'Offline Sync', 'RefreshCw', 'Manage data synchronization queues for offline deployments.', 'districts', ['District', 'Last Synced', 'Pending Records', 'Status']),
    ('profile', 'Profile', 'UserCircle', 'Manage your State Health Officer profile.', 'districts', []),
    ('settings', 'Settings', 'Settings', 'Configure state portal settings.', 'districts', [])
]

template = """'use client';

import React from 'react';
import {{ useAuth }} from '@/providers/AuthProvider';
import {{ PageHeader, EmptyState }} from '@/features/shared';
import {{ icons }} from '@/design-system/icons';
import {{ ShieldCheck, MousePointer2 }} from 'lucide-react';
import {{ isDemoUser }} from '@/config/demoAccounts';
import {{ useStateModuleData }} from '@/features/state/hooks/useStateModuleData';

export default function {ModuleName}Page() {{
  const {{ user }} = useAuth();
  const isDemo = isDemoUser(user?.email);
  const {{ data, isLoading }} = useStateModuleData(user?.uid || '');

  if (!isDemo || !data) {{
    return (
      <div className="space-y-6">
        <PageHeader 
          title="{Title}" 
          description="{Desc}" 
        />
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8">
          <EmptyState 
            icon={{icons.{Icon} || ShieldCheck}}
            title="No Data Available"
            description="This module requires active state-level data integration. Contact administration to configure your data pipelines."
          />
        </div>
      </div>
    );
  }}

  const {{ {DataVar} }} = data;

  return (
    <div className="space-y-6">
      <PageHeader 
        title="{Title}" 
        description="{Desc}" 
      />
      {Content}
    </div>
  );
}}
"""

table_template = """
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden shadow-sm">
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/50 flex justify-between items-center">
          <h2 className="font-bold text-slate-800 dark:text-slate-100">{Title} Overview</h2>
          <button className="px-3 py-1.5 text-xs font-semibold bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 dark:bg-blue-900/30 dark:text-blue-400">Export CSV</button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 uppercase bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800">
              <tr>
                {Headers}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {{ {DataVar}.map((item: any, i: number) => (
                <tr key={{i}} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                  <td className="px-4 py-3 font-medium text-slate-900 dark:text-slate-100">{{item.name || item.title || item.resource || item.id || '{Title} Item ' + i}}</td>
                  <td className="px-4 py-3 text-slate-600 dark:text-slate-400">{{item.district || item.from || item.population || 'All Districts'}}</td>
                  <td className="px-4 py-3 text-slate-600 dark:text-slate-400">{{item.hospitals || item.to || item.beds || item.severity || 'N/A'}}</td>
                  <td className="px-4 py-3 text-slate-600 dark:text-slate-400">{{item.phcs || item.quantity || item.healthScore || item.time || 'N/A'}}</td>
                  <td className="px-4 py-3">
                    <span className={{`px-2 py-1 text-xs font-semibold rounded-lg ${{
                      item.status === 'green' || item.status === 'optimal' || item.status === 'completed' ? 'bg-emerald-50 text-emerald-600 dark:bg-emerald-900/30' :
                      item.status === 'yellow' || item.status === 'warning' || item.status === 'pending' || item.severity === 'medium' ? 'bg-amber-50 text-amber-600 dark:bg-amber-900/30' :
                      item.status === 'red' || item.status === 'critical' || item.severity === 'high' ? 'bg-red-50 text-red-600 dark:bg-red-900/30' :
                      'bg-slate-100 text-slate-600 dark:bg-slate-800'
                    }}`}}>
                      {{item.status || item.severity || 'Active'}}
                    </span>
                  </td>
                </tr>
              ))}}
            </tbody>
          </table>
        </div>
      </div>
"""

cards_template = """
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {{ {DataVar}.map((item: any, i: number) => (
          <div key={{i}} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-4">
              <div className="p-2 bg-blue-50 dark:bg-blue-900/30 rounded-lg text-blue-600">
                <icons.{Icon} className="h-5 w-5" />
              </div>
              <span className={{`px-2 py-1 text-[10px] font-bold uppercase rounded ${{
                item.status === 'green' || item.status === 'optimal' || item.status === 'completed' ? 'bg-emerald-50 text-emerald-600 border border-emerald-200' :
                item.status === 'yellow' || item.status === 'warning' || item.status === 'pending' || item.severity === 'medium' ? 'bg-amber-50 text-amber-600 border border-amber-200' :
                item.status === 'red' || item.status === 'critical' || item.severity === 'high' ? 'bg-red-50 text-red-600 border border-red-200' :
                'bg-slate-50 text-slate-600 border border-slate-200'
              }}`}}>
                {{item.status || item.severity || 'Active'}}
              </span>
            </div>
            <h3 className="font-bold text-lg text-slate-900 dark:text-white">{{item.name || item.title || item.resource || '{Title}'}}</h3>
            <p className="text-sm text-slate-500 mb-4">{{item.district || item.from || 'Statewide Integration'}}</p>
            
            <div className="grid grid-cols-2 gap-2 text-sm">
              <div className="bg-slate-50 dark:bg-slate-800 p-2 rounded-lg">
                <span className="block text-xs text-slate-400">Metric 1</span>
                <span className="font-semibold">{{item.hospitals || item.quantity || item.bedsOccupied || 'N/A'}}</span>
              </div>
              <div className="bg-slate-50 dark:bg-slate-800 p-2 rounded-lg">
                <span className="block text-xs text-slate-400">Metric 2</span>
                <span className="font-semibold">{{item.healthScore || item.doctors || item.time || 'N/A'}}</span>
              </div>
            </div>
          </div>
        ))}}
      </div>
"""

for route, title, icon, desc, data_var, headers in routes:
    module_name = ''.join(word.capitalize() for word in route.split('-'))
    
    if len(headers) > 0:
        if route in ['hospitals', 'analytics', 'ai', 'surveillance']:
            content_str = cards_template.format(DataVar=data_var, Title=title, Icon=icon)
        else:
            headers_str = '\\n                '.join(f'<th className="px-4 py-3">{h}</th>' for h in headers)
            content_str = table_template.format(DataVar=data_var, Headers=headers_str, Title=title)
    else:
        # Profile/Settings dummy
        content_str = f"""
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8 max-w-2xl">
          <div className="flex items-center gap-4 mb-8">
            <div className="h-16 w-16 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-2xl font-bold text-slate-400">
              SO
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">Dr. State Officer</h2>
              <p className="text-slate-500">Chief Medical Officer, State Department</p>
            </div>
          </div>
          <div className="space-y-4">
            <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-100 dark:border-slate-800">
              <label className="text-xs font-bold text-slate-500 uppercase">Email</label>
              <div className="font-medium">{{{'{'}user?.email || 'state.demo@gmail.com'{'}'}}}</div>
            </div>
            <div className="p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-slate-100 dark:border-slate-800">
              <label className="text-xs font-bold text-slate-500 uppercase">Role Permissions</label>
              <div className="font-medium">State Administrator (Level 1)</div>
            </div>
          </div>
        </div>
        """

    content = template.format(ModuleName=module_name, Title=title, Desc=desc, Icon=icon, DataVar=data_var, Content=content_str)
    
    path = f'src/app/dashboard/(state)/state/{route}/page.tsx'
    with open(path, 'w') as f:
        f.write(content)
