export const APPOINTMENT_AUDIT_ACTIONS = {
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CHECKED_IN: 'APPOINTMENT_CHECKED_IN',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  WAITING_LIST_JOINED: 'WAITING_LIST_JOINED',
  WAITING_LIST_PROMOTED: 'WAITING_LIST_PROMOTED',
} as const;

export type AppointmentAuditAction = typeof APPOINTMENT_AUDIT_ACTIONS[keyof typeof APPOINTMENT_AUDIT_ACTIONS];
