import { UserRole } from './roles';
import { ROUTES } from './routes';

export interface NavItem {
  title: string;
  href: string;
  icon: string; // Lucide icon identifier string
}

export const ROLE_NAVIGATION: Record<UserRole, NavItem[]> = {
  citizen: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.CITIZEN.HOME, icon: 'Home' },
    { title: 'Appointments', href: ROUTES.DASHBOARD.CITIZEN.APPOINTMENTS, icon: 'Calendar' },
    { title: 'Doctors', href: '/dashboard/citizen/doctors', icon: 'Stethoscope' },
    { title: 'Hospitals', href: '/dashboard/citizen/hospitals', icon: 'Building2' },
    { title: 'Prescriptions', href: ROUTES.DASHBOARD.CITIZEN.PRESCRIPTIONS, icon: 'FileText' },
    { title: 'Reports', href: '/dashboard/citizen/reports', icon: 'BarChart2' },
    { title: 'Family Members', href: ROUTES.DASHBOARD.CITIZEN.FAMILY, icon: 'Users' },
    { title: 'Notifications', href: '/dashboard/citizen/notifications', icon: 'Bell' },
    { title: 'Profile', href: '/dashboard/citizen/profile', icon: 'UserCircle' },
    { title: 'Settings', href: '/dashboard/citizen/settings', icon: 'Settings' },
  ],
  doctor: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.DOCTOR.HOME, icon: 'LayoutDashboard' },
    { title: 'Calendar', href: '/dashboard/doctor/calendar', icon: 'Calendar' },
    { title: 'Patients', href: ROUTES.DASHBOARD.DOCTOR.PATIENTS, icon: 'UserSquare2' },
    { title: 'Prescriptions', href: '/dashboard/doctor/prescriptions', icon: 'FileText' },
    { title: 'Lab Orders', href: '/dashboard/doctor/lab-orders', icon: 'FlaskConical' },
    { title: 'Follow Ups', href: '/dashboard/doctor/follow-ups', icon: 'RefreshCw' },
    { title: 'AI Assistant', href: '/dashboard/doctor/ai-summary', icon: 'Bot' },
    { title: 'Profile', href: '/dashboard/doctor/profile', icon: 'UserCircle' },
    { title: 'Settings', href: '/dashboard/doctor/settings', icon: 'Settings' },
  ],
  hospital_admin: [
    { title: 'Dashboard', href: '/dashboard/hospital', icon: 'LayoutDashboard' },
    { title: 'Patients', href: '/dashboard/hospital/patients', icon: 'Users' },
    { title: 'Doctors', href: '/dashboard/hospital/doctors', icon: 'UserSquare2' },
    { title: 'Appointments', href: '/dashboard/hospital/appointments', icon: 'Calendar' },
    { title: 'Departments', href: '/dashboard/hospital/departments', icon: 'Building' },
    { title: 'Beds', href: '/dashboard/hospital/beds', icon: 'Bed' },
    { title: 'Rooms', href: '/dashboard/hospital/rooms', icon: 'Home' },
    { title: 'Inventory', href: '/dashboard/hospital/inventory', icon: 'Package' },
    { title: 'Pharmacy', href: '/dashboard/hospital/pharmacy', icon: 'Pill' },
    { title: 'Laboratory', href: '/dashboard/hospital/laboratory', icon: 'FlaskConical' },
    { title: 'Reports', href: '/dashboard/hospital/reports', icon: 'BarChart2' },
    { title: 'AI Insights', href: '/dashboard/hospital/ai-health-score', icon: 'Bot' },
    { title: 'Profile', href: '/dashboard/hospital/settings', icon: 'Settings' },
  ],
  nurse: [
    { title: 'Dashboard', href: '/dashboard/nurse', icon: 'LayoutDashboard' },
    { title: 'Assigned Patients', href: '/dashboard/nurse/patients', icon: 'Users' },
    { title: 'Ward Dashboard', href: '/dashboard/nurse/ward', icon: 'Building' },
    { title: 'Bed Assignments', href: '/dashboard/nurse/beds', icon: 'Bed' },
    { title: 'Vital Signs', href: '/dashboard/nurse/vitals', icon: 'Activity' },
    { title: 'Medications', href: '/dashboard/nurse/medications', icon: 'Pill' },
    { title: 'Care Notes', href: '/dashboard/nurse/notes', icon: 'FileText' },
    { title: 'Emergency', href: '/dashboard/nurse/emergency', icon: 'AlertTriangle' },
  ],
  pharmacist: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.PHARMACY.HOME, icon: 'LayoutDashboard' },
    { title: 'Dispensing Queue', href: ROUTES.DASHBOARD.PHARMACY.DISPENSE, icon: 'FileSearch2' },
    { title: 'Inventory', href: ROUTES.DASHBOARD.PHARMACY.INVENTORY, icon: 'Package' },
    { title: 'Medicines', href: '/dashboard/pharmacy/medicines', icon: 'Pill' },
    { title: 'Expiry Tracker', href: '/dashboard/pharmacy/expiry', icon: 'AlertTriangle' },
    { title: 'Reports', href: '/dashboard/pharmacy/reports', icon: 'BarChart2' },
    { title: 'AI Forecast', href: '/dashboard/pharmacy/ai-forecast', icon: 'Bot' },
  ],
  lab_technician: [
    { title: 'Overview', href: ROUTES.DASHBOARD.LABORATORY.HOME, icon: 'Home' },
    { title: 'Test Orders', href: ROUTES.DASHBOARD.LABORATORY.ORDERS, icon: 'ClipboardList' },
    { title: 'Sample Collection', href: ROUTES.DASHBOARD.LABORATORY.SAMPLES, icon: 'Syringe' },
    { title: 'Processing Queue', href: ROUTES.DASHBOARD.LABORATORY.PROCESSING, icon: 'Activity' },
    { title: 'Result Entry', href: ROUTES.DASHBOARD.LABORATORY.RESULTS, icon: 'FileText' },
    { title: 'Completed Reports', href: ROUTES.DASHBOARD.LABORATORY.REPORTS, icon: 'CheckCircle2' },
    { title: 'Quality Control', href: ROUTES.DASHBOARD.LABORATORY.QC, icon: 'Shield' },
    { title: 'Equipment Status', href: ROUTES.DASHBOARD.LABORATORY.EQUIPMENT, icon: 'Settings' },
    { title: 'Inventory', href: ROUTES.DASHBOARD.LABORATORY.INVENTORY, icon: 'Package' },
    { title: 'Patients', href: ROUTES.DASHBOARD.LABORATORY.PATIENTS, icon: 'Users' },
    { title: 'Analytics', href: ROUTES.DASHBOARD.LABORATORY.ANALYTICS, icon: 'BarChart2' },
    { title: 'Offline Sync', href: ROUTES.DASHBOARD.LABORATORY.SYNC, icon: 'RefreshCw' },
    { title: 'Profile', href: ROUTES.DASHBOARD.LABORATORY.PROFILE, icon: 'UserCircle' },
    { title: 'Settings', href: ROUTES.DASHBOARD.LABORATORY.SETTINGS, icon: 'Settings' },
  ],
  district_admin: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.DISTRICT.HOME, icon: 'LayoutDashboard' },
    { title: 'Hospitals', href: '/dashboard/district/hospitals', icon: 'Building2' },
    { title: 'PHCs', href: '/dashboard/district/phcs', icon: 'MapPin' },
    { title: 'CHCs', href: '/dashboard/district/chcs', icon: 'MapPin' },
    { title: 'Medicine Monitor', href: '/dashboard/district/medicine-monitoring', icon: 'Pill' },
    { title: 'Bed Monitor', href: '/dashboard/district/bed-monitoring', icon: 'Bed' },
    { title: 'Doctor Attendance', href: '/dashboard/district/doctor-attendance', icon: 'UserCheck' },
    { title: 'Critical Alerts', href: '/dashboard/district/alerts', icon: 'AlertTriangle' },
    { title: 'Redistribution', href: ROUTES.DASHBOARD.DISTRICT.REDISTRIBUTION, icon: 'ArrowLeftRight' },
    { title: 'AI Center', href: '/dashboard/district/ai', icon: 'Bot' },
    { title: 'Reports', href: '/dashboard/district/reports', icon: 'BarChart2' },
  ],
  state_admin: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.STATE.HOME, icon: 'LayoutDashboard' },
    { title: 'District Monitoring', href: '/dashboard/state/districts', icon: 'Map' },
    { title: 'Hospitals', href: '/dashboard/state/hospitals', icon: 'Building2' },
    { title: 'PHCs', href: '/dashboard/state/phcs', icon: 'MapPin' },
    { title: 'CHCs', href: '/dashboard/state/chcs', icon: 'MapPin' },
    { title: 'Medicine Supply Chain', href: '/dashboard/state/medicine', icon: 'Pill' },
    { title: 'Bed Capacity', href: '/dashboard/state/beds', icon: 'Bed' },
    { title: 'Doctor Workforce', href: '/dashboard/state/workforce', icon: 'UserCheck' },
    { title: 'Disease Surveillance', href: '/dashboard/state/surveillance', icon: 'Activity' },
    { title: 'Emergency Response', href: '/dashboard/state/emergency', icon: 'AlertTriangle' },
    { title: 'AI Command Center', href: '/dashboard/state/ai', icon: 'Bot' },
    { title: 'Resource Allocation', href: '/dashboard/state/allocation', icon: 'ArrowLeftRight' },
    { title: 'Analytics', href: '/dashboard/state/analytics', icon: 'BarChart2' },
    { title: 'Reports', href: '/dashboard/state/reports', icon: 'FileText' },
    { title: 'Policies', href: '/dashboard/state/policies', icon: 'ShieldCheck' },
    { title: 'Notifications', href: '/dashboard/state/notifications', icon: 'Bell' },
    { title: 'Offline Sync', href: '/dashboard/state/sync', icon: 'RefreshCw' },
    { title: 'Profile', href: '/dashboard/state/profile', icon: 'UserCircle' },
    { title: 'Settings', href: '/dashboard/state/settings', icon: 'Settings' },
  ],
  asha_worker: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.ASHA.HOME, icon: 'Home' },
    { title: 'Assigned Families', href: '/dashboard/asha/families', icon: 'Users' },
    { title: 'Household Visits', href: '/dashboard/asha/visits', icon: 'MapPin' },
    { title: 'Pregnancy Tracking', href: '/dashboard/asha/pregnancy', icon: 'Baby' },
    { title: 'Maternal Care', href: '/dashboard/asha/maternal', icon: 'HeartPulse' },
    { title: 'Child Health & Immunization', href: '/dashboard/asha/child-health', icon: 'Syringe' },
    { title: 'High Risk Patients', href: '/dashboard/asha/high-risk', icon: 'AlertTriangle' },
    { title: 'Chronic Disease Follow-up', href: '/dashboard/asha/chronic', icon: 'Activity' },
    { title: 'Health Surveys', href: '/dashboard/asha/surveys', icon: 'ClipboardList' },
    { title: 'Medicine Distribution', href: '/dashboard/asha/medicine', icon: 'Pill' },
    { title: 'Referrals', href: '/dashboard/asha/referrals', icon: 'ArrowRightCircle' },
    { title: 'Health Education', href: '/dashboard/asha/education', icon: 'BookOpen' },
    { title: 'Community Alerts', href: '/dashboard/asha/alerts', icon: 'Bell' },
    { title: 'Reports', href: '/dashboard/asha/reports', icon: 'BarChart2' },
    { title: 'Offline Sync', href: '/dashboard/asha/sync', icon: 'RefreshCcw' },
    { title: 'Profile', href: '/dashboard/asha/profile', icon: 'UserCircle' },
    { title: 'Settings', href: '/dashboard/asha/settings', icon: 'Settings' },
  ],
  super_admin: [
    { title: 'Dashboard', href: ROUTES.DASHBOARD.HOME, icon: 'LayoutDashboard' },
    { title: 'Platform Overview', href: '/dashboard/admin/platform', icon: 'Globe' },
    { title: 'Users', href: '/dashboard/admin/users', icon: 'Users' },
    { title: 'Healthcare Organizations', href: '/dashboard/admin/organizations', icon: 'Building2' },
    { title: 'Role Management', href: '/dashboard/admin/roles', icon: 'ShieldCheck' },
    { title: 'Hospitals', href: '/dashboard/admin/hospitals', icon: 'Building2' },
    { title: 'PHCs', href: '/dashboard/admin/phcs', icon: 'MapPin' },
    { title: 'CHCs', href: '/dashboard/admin/chcs', icon: 'MapPin' },
    { title: 'Districts', href: '/dashboard/admin/districts', icon: 'Map' },
    { title: 'States', href: '/dashboard/admin/states', icon: 'Map' },
    { title: 'AI Management', href: '/dashboard/admin/ai', icon: 'Bot' },
    { title: 'System Health', href: '/dashboard/admin/health', icon: 'Activity' },
    { title: 'API Monitoring', href: '/dashboard/admin/api', icon: 'Terminal' },
    { title: 'Audit Logs', href: '/dashboard/admin/audit', icon: 'ClipboardList' },
    { title: 'Security Center', href: '/dashboard/admin/security', icon: 'Shield' },
    { title: 'Notifications', href: '/dashboard/admin/notifications', icon: 'Bell' },
    { title: 'Analytics', href: '/dashboard/admin/analytics', icon: 'BarChart2' },
    { title: 'Reports', href: '/dashboard/admin/reports', icon: 'FileText' },
    { title: 'Database Monitoring', href: '/dashboard/admin/database', icon: 'Database' },
    { title: 'Storage', href: '/dashboard/admin/storage', icon: 'HardDrive' },
    { title: 'Backups', href: '/dashboard/admin/backups', icon: 'Save' },
    { title: 'Platform Settings', href: '/dashboard/admin/settings', icon: 'Settings' },
    { title: 'Feature Flags', href: '/dashboard/admin/features', icon: 'ToggleRight' },
    { title: 'Offline Sync', href: '/dashboard/admin/sync', icon: 'RefreshCw' },
    { title: 'Profile', href: '/dashboard/admin/profile', icon: 'UserCircle' },
    { title: 'Preferences', href: '/dashboard/admin/preferences', icon: 'Sliders' },
  ],
};

export function getNavigationForRole(role: UserRole): NavItem[] {
  return ROLE_NAVIGATION[role] || [];
}
